# Generated by Django 3.0.5 on 2020-05-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='torenums',
            new_name='storenums',
        ),
    ]
