# Generated by Django 3.0.5 on 2020-05-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200503_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pmdesc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specifics',
            field=models.CharField(max_length=64),
        ),
    ]
