# Generated by Django 3.0.5 on 2020-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
