# Generated by Django 3.0.5 on 2020-05-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='o_remarks',
            field=models.TextField(default='未备注'),
        ),
    ]
