# Generated by Django 3.0.5 on 2020-05-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='u_defaultaddress',
            field=models.IntegerField(default=0),
        ),
    ]
